language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm run nyc:test
  - npm run nyc:check
  - npm run nyc:report
after_success:
  - ./node_modules/.bin/codecov
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
